spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: config-server
server:
  port: 8769


eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://xujian:123456@peer1:7001/eureka