server:
  port: 7003
spring:
  application:
    name: eureka_consumer
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://xujian:123456@peer1:7001/eureka,http://xujian:123456@peer2:7701/eureka


