server:
  port: 9411
# 最佳实践：springcloud应用都要指定application.name
spring:
  application:
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true # 当bean重复定义时允许相同key情况下beanDefinition实例的覆盖

eureka:
  client:
    serviceUrl:
      # 指定服务注册中心的地址
      defaultZone: http://xujian:123456@peer1:7001/eureka
#      上面是eureka单机注册中心。下面是eureka集群模式
#      defaultZone: http://admin:123456@eureka2:8001/eureka/,http://admin:123456@eureka3:8002/eureka/,http://admin:123456@eureka2:8003/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false