server:
  port: 7702
spring:
  application:
    name: eurekaproduce
  boot:
    admin:
      client:
        url: "http://localhost:9997"
      period: 600
  management:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: ALWAYS
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://xujian:123456@peer1:7001/eureka

