spring:
  application:
    name: admin-server
  profiles:
    active:
      - secure

server:
  port: 9997

# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10  # 表示eureka client发送心跳给server端的频率
    health-check-url-path: /actuator/health # 健康检查页面的URL，相对路径，默认使用 HTTP 访问，如果需要使用 HTTPS则需要使用绝对路径配置
  client:
    registryFetchIntervalSeconds: 5 # 表示eureka client 间隔多久去拉取服务注册信息，默认是30秒。
    serviceUrl:
      defaultZone: http://xujian:123456@peer1:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 因为actuator默认只支持端点 /health、/info。 *标识暴露所有端点
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "user"
      password: "password"
eureka:
  instance:
    metadata-map:
      user.name: "user"         #These two are needed so that the server
      user.password: "password" #can access the protected client endpoints