server:
  port: 8001
spring:
  application:
    name: gateway-web
  redis:
    host: 120.76.135.172
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
            - id: APP
              # [1] 非负载均衡
              #uri: http://localhost:8081
              # [2]客户端负载均衡
              uri: lb://APP
              # 断言
              predicates:
                # [1]host 过滤,针对域名
                #- Host=xujiangateway.com**
                # [2]路径匹配过滤
                 - Path=/nima/setSession/**
                #- Path=/**
                # [3] StripPrefix 过滤配置
              filters:
                - StripPrefix=1
                #- PrefixPath=/setSession
                - name:  RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 1


eureka:
  client:
    service-url:
      defaultZone: http://xujian:123456@127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true


